### ISSUE TITLE
src/Data/Serialization.h fails to compile with Boost 1.59.0

### ISSUE THREAD

**Issue by susilehtola** [nutjunkie/IQmol#14]
The development tree of Fedora has Boost 1.59.0, against which IQmol fails to build.

This problem was already reported in issue #8.

**Comment by rathann** [comment]
Same with boost 1.60.0, which is the current release.

**Comment by susilehtola** [comment]
I've solved the issue by commenting out the offending code, as per discussions with Andrew.
