### ISSUE TITLE
libopenbabel.so.4 and libopenbabel.so.5

### ISSUE THREAD

**Issue by stefabat** [nutjunkie/IQmol#17]
Hi

I tried to use the binary version on Arch Linux, with openbabel installed from the official repos of the distribution, but IQmol complains while opening due to a missing libopenbabel.so.4 library.
I agree with that complaint, since that library does not exist, in Arch the openbabel library is called libopenbabel.so.5
with openbabel version 2.4.1

Is there an easy fix?
A simple symlink does not work..

**Comment by ZQyou** [comment]
Hi Stefano,

If you installed IQmol 2.8 from http://iqmol.org/downloads.html, the libraries and plugins of the older openbabel are included in the package. I don't have openbabel 2.4.1 on my Ubuntu, but I tried to remove openbabel library  and no complaint. If you installed IQmol in default path, which is /opt/IQmol-2.8, can you try to run  /opt/IQmol-2.8/cde-root/opt/IQmol/iqmol.sh and see if there is still a complaint.

**Comment by stefabat** [comment]
Sorry, my bad.. I haven't even tried to run the bash script, I was trying to launch the executable directly and thus probably the openbabel lib that comes with the package was not set in the path.
Thank you for the fast reply though.
