### ISSUE TITLE
Job submission via Q-Chem server fails

### ISSUE THREAD

**Issue by felixplasser** [nutjunkie/IQmol#42]
Hi, I am just running a little summer course where I wanted the students to run a few jobs via IQmol and the Q-Chem server.

In IQmol 2.14, I get an error message once I click submit via the Q-Chem server:
`Job submission failed: Unknown error`

I took a quick look at the recent commits and it seems that the problem lies in [18f457ac5a9fb19b]. I can fix the problem in IQmol if I change the server name back to `QChem` rather than `Q-Chem`. Don't know why this would make a difference but it seems to on my computer.

Cheers,
Felix

**Comment by nutjunkie** [comment]
Hi Felix,

I am glad you were able to find a work-around, but I am a bit puzzled by your fix as the name of the server shouldn't have had any effect.  If you updated your version of IQmol then there may have been a problem loading your previous server settings.  In this case creating a new HTTP server should load the correct settings and allow you to proceed.

Regards,
Andrew
________________________________

**Comment by felixplasser** [comment]
Hi Andrew, thanks for getting back! I double checked: It looks like the reason was that editing the server also automatically changed the port number. If I change the port number manually, then it works also with the original server name (as you'd expect).
-Felix
